#!/bin/bash
# Vorachet Jaroensawas 

VERSION=v0.3
FROGLET_MODELS_FOLDER=$(pwd)/models
FROGLET_GENERATORS_FOLDER=$(pwd)/generators
FROGLET_OUTPUT_FOLDER=$(pwd)/output

printf "\n  FROGLET_MODELS_FOLDER = ${FROGLET_MODELS_FOLDER}"
printf "\n  FROGLET_GENERATORS_FOLDER = ${FROGLET_GENERATORS_FOLDER}"
printf "\n  FROGLET_OUTPUT_FOLDER = ${FROGLET_OUTPUT_FOLDER}\n"

exitIfIGslProgramUninstalled() {
    if ! gsl -v  &> /dev/null
    then
        echo ""
        echo "gsl program could not be found (installation guide https://github.com/imatix/gsl)"
        echo ""
        exit
    else
        echo -e "\xE2\x9C\x94  Found GSL at $(which gsl)"
    fi
}
exitIfIndexGeneratorUndefined() {
    GENERATOR_INDEX_FILE=${FROGLET_GENERATORS_FOLDER}/index.gsl
    if [ ! -f "${GENERATOR_INDEX_FILE}" ]; then
        echo ""
        echo "Cannot find Generator Index File"
        echo "Expected file path = ${GENERATOR_INDEX_FILE}"
        echo ""
        exit
    else
        echo -e "\xE2\x9C\x94  Found Generator Index File at ${GENERATOR_INDEX_FILE}"
    fi
}

echo ""

exitIfIGslProgramUninstalled

exitIfIndexGeneratorUndefined

printf "\nChoose generator:\n"

cd ${FROGLET_GENERATORS_FOLDER}
select g in * ; do test -n "$g" && break; echo ">>> Invalid Selection"; done
generator=$g


cd ${FROGLET_MODELS_FOLDER}
printf "\nChoose model:\n"
select m in * ; do test -n "$m" && break; echo ">>> Invalid Selection"; done
model=$m

mkdir -p ${FROGLET_OUTPUT_FOLDER}

clear 

echo -e ""
echo -e ""
echo -e ""
echo -e "\xE2\x9C\x94  Target Generator ${FROGLET_GENERATORS_FOLDER}/${generator}"
echo -e "\xE2\x9C\x94  Target Model ${FROGLET_MODELS_FOLDER}/${model}"
echo -e "\xE2\x9C\x94  Target Output Folder ${FROGLET_OUTPUT_FOLDER}"

cd ${FROGLET_GENERATORS_FOLDER}/
echo -e ""
echo -e ""
echo -e "Generating..."
echo -e ""

model_without_extension=$(echo "$model" | cut -f 1 -d '.')
gsl -a -p -q -script:index ${FROGLET_MODELS_FOLDER}/$model ${FROGLET_OUTPUT_FOLDER} ${model_without_extension}

echo -e ""
echo -e "\xE2\x9C\x94  Done"
echo -e ""
echo -e "Enjoy using Froglet ${VERSION}! "
